#.travis.yml
language: java

jdk:
  - oraclejdk8
  - openjdk7

install:
  - mvn clean install -DskipTests=true -B -U -e
  - sh ./tools/check_format.sh

script:
  - mvn clean package -Dmaven.javadoc.skip=true
  - mvn clean package -Park -Dmaven.javadoc.skip=true

after_success:
  - bash <(curl -s https://codecov.io/bash)
